require('./gulp-tasks/default.js');
require('./gulp-tasks/js-concat.js');
require('./gulp-tasks/js-min.js');
require('./gulp-tasks/sass.js');
require('./gulp-tasks/css-min.js');
require('./gulp-tasks/style.js');
require('./gulp-tasks/browser.js');
require('./gulp-tasks/inject.js');
require('./gulp-tasks/build.js');